# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1365824625);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1352939333);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1365824745);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 389120);
user_pref("browser.download.lastDir", "/home/saasbook/Downloads");
user_pref("browser.download.save_converter_index", 0);
user_pref("browser.migration.version", 6);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.buildID", "20120423123513");
user_pref("browser.startup.homepage_override.mstone", "rv:12.0");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 12);
user_pref("extensions.enabledAddons", "firebug@software.joehewitt.com:1.9.1,{c45c406e-ab73-11d8-be73-000a95be3b12}:1.1.9,globalmenu@ubuntu.com:2.0.6,ubufox@ubuntu.com:1.0.4,langpack-en-GB@firefox.mozilla.org:12.0,langpack-en-ZA@firefox.mozilla.org:12.0,{972ce4c6-7e08-4474-a285-3208198ce6fd}:12.0");
user_pref("extensions.firebug.addonBarOpened", true);
user_pref("extensions.firebug.currentVersion", "1.9.2");
user_pref("extensions.firebug.previousPlacement", 3);
user_pref("extensions.firebug.toolbarCustomizationDone", true);
user_pref("extensions.hotfix.certs.1.sha1Fingerprint", "CA:C4:7D:BF:63:4D:24:E9:DC:93:07:2F:E3:C8:EA:6D:C3:94:6E:89");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1337106981000}}},{\"name\":\"app-global\",\"addons\":{\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1335196620000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox/extensions/globalmenu@ubuntu.com\",\"mtime\":1337106868000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1335196620000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1337106870000}}},{\"name\":\"app-profile\",\"addons\":{\"firebug@software.joehewitt.com\":{\"descriptor\":\"/home/saasbook/.mozilla/firefox/h9xf1jt0.default/extensions/firebug@software.joehewitt.com.xpi\",\"mtime\":1352505146000},\"{c45c406e-ab73-11d8-be73-000a95be3b12}\":{\"descriptor\":\"/home/saasbook/.mozilla/firefox/h9xf1jt0.default/extensions/{c45c406e-ab73-11d8-be73-000a95be3b12}.xpi\",\"mtime\":1352505146000}}}]");
user_pref("extensions.lastAppVersion", "12.0");
user_pref("extensions.lastPlatformVersion", "12.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.webdeveloper.resize.1.description", "800x600");
user_pref("extensions.webdeveloper.resize.1.height", 600);
user_pref("extensions.webdeveloper.resize.1.width", 800);
user_pref("extensions.webdeveloper.version", "1.2");
user_pref("idle.lastDailyNotification", 1365825096);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1365825096);
user_pref("places.history.expiration.transient_current_max_pages", 26267);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1365825096);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1368416511);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
